#!/bin/bash
SERVER_PORT=$(printenv SM_SERVER_PORT)
MONGODB_PORT=$(printenv SM_MONGODB_PORT)
SM_PRIVATE_KEY=$(printenv SM_PRIVATE_KEY)
SM_CONTRACT_ADDRESS=$(printenv SM_CONTRACT_ADDRESS)
GANACHE_PORT=$(printenv GANACHE_PORT)
java -DSERVER_PORT=${SERVER_PORT} -DSM_CONTRACT_ADDRESS=${SM_CONTRACT_ADDRESS} -DMONGODB_PORT=${MONGODB_PORT}  -DSM_PRIVATE_KEY=${SM_PRIVATE_KEY} -DGANACHE_PORT=${GANACHE_PORT} -jar smartContract.jar 

