#!/bin/bash
SERVER_PORT=$(printenv SM_SERVER_PORT)
MONGODB_PORT=$(printenv SM_MONGODB_PORT)
PAY_PRIVATE_KEY=$(printenv PAY_PRIVATE_KEY)
PAY_CONTRACT_ADDRESS=$(printenv PAY_CONTRACT_ADDRESS)
GANACHE_PORT=$(printenv GANACHE_PORT)

java -DSERVER_PORT=${SERVER_PORT} -DMONGODB_PORT=${MONGODB_PORT} -DPAY_CONTRACT_ADDRESS=${PAY_CONTRACT_ADDRESS}  -DPAY_PRIVATE_KEY=${PAY_PRIVATE_KEY} -DGANACHE_PORT=${GANACHE_PORT} -jar smartContract.jar 

